
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 26 20:25:58 CST 2017
//----------------------------------------------------

package p_minipascal;

import necessities.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Mar 26 20:25:58 CST 2017
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\123\000\002\002\007\000\002\002\004\000\002\003" +
    "\005\000\002\047\004\000\002\004\004\000\002\004\002" +
    "\000\002\005\005\000\002\005\002\000\002\045\005\000" +
    "\002\045\005\000\002\013\004\000\002\013\002\000\002" +
    "\014\005\000\002\046\006\000\002\046\012\000\002\050" +
    "\007\000\002\050\005\000\002\006\003\000\002\006\003" +
    "\000\002\007\010\000\002\010\006\000\002\011\003\000" +
    "\002\012\003\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\003\000\002\015\005\000\002\015" +
    "\004\000\002\043\005\000\002\043\004\000\002\016\003" +
    "\000\002\016\003\000\002\017\003\000\002\017\003\000" +
    "\002\017\003\000\002\017\003\000\002\021\005\000\002" +
    "\022\003\000\002\023\003\000\002\024\006\000\002\025" +
    "\003\000\002\026\006\000\002\044\005\000\002\044\003" +
    "\000\002\027\003\000\002\020\003\000\002\020\003\000" +
    "\002\020\003\000\002\020\003\000\002\020\003\000\002" +
    "\030\006\000\002\030\010\000\002\031\006\000\002\051" +
    "\013\000\002\052\006\000\002\032\003\000\002\032\005" +
    "\000\002\032\005\000\002\032\005\000\002\032\005\000" +
    "\002\032\005\000\002\032\005\000\002\033\003\000\002" +
    "\033\005\000\002\033\005\000\002\033\004\000\002\033" +
    "\004\000\002\034\003\000\002\034\005\000\002\034\005" +
    "\000\002\035\003\000\002\035\003\000\002\035\003\000" +
    "\002\035\003\000\002\035\005\000\002\035\004\000\002" +
    "\036\003\000\002\036\003\000\002\037\006\000\002\040" +
    "\003\000\002\041\003\000\002\042\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\244\000\004\031\005\001\002\000\004\002\246\001" +
    "\002\000\004\062\006\001\002\000\004\032\007\001\002" +
    "\000\010\010\010\014\ufffc\026\ufffc\001\002\000\010\014" +
    "\ufffa\026\ufffa\062\235\001\002\000\006\014\015\026\ufff6" +
    "\001\002\000\004\035\013\001\002\000\004\002\001\001" +
    "\002\000\006\010\010\026\ufffc\001\002\000\004\062\171" +
    "\001\002\000\006\014\015\026\ufff6\001\002\000\004\026" +
    "\020\001\002\000\024\015\035\017\026\021\047\023\050" +
    "\026\020\027\033\036\022\037\036\062\037\001\002\000" +
    "\004\035\uffff\001\002\000\004\044\164\001\002\000\006" +
    "\016\uffd0\032\uffd0\001\002\000\006\016\uffd1\032\uffd1\001" +
    "\002\000\006\016\uffdb\032\uffdb\001\002\000\022\040\065" +
    "\041\060\044\072\056\071\062\067\063\074\064\061\065" +
    "\063\001\002\000\006\016\uffd2\032\uffd2\001\002\000\006" +
    "\016\uffe1\032\uffe1\001\002\000\004\046\156\001\002\000" +
    "\006\016\uffdf\032\uffdf\001\002\000\010\016\uffe5\032\uffe5" +
    "\035\uffe5\001\002\000\006\016\uffd3\032\uffd3\001\002\000" +
    "\022\040\065\041\060\044\072\056\071\062\067\063\074" +
    "\064\061\065\063\001\002\000\004\044\142\001\002\000" +
    "\012\016\uffda\032\uffda\046\uffaf\061\uffaf\001\002\000\050" +
    "\016\uffb0\020\uffb0\025\uffb0\032\uffb0\034\uffb0\040\uffb0\041" +
    "\uffb0\042\uffb0\043\uffb0\045\uffb0\046\uffb0\047\uffb0\050\uffb0" +
    "\051\uffb0\052\uffb0\053\uffb0\054\uffb0\055\uffb0\061\uffb0\001" +
    "\002\000\006\016\uffe0\032\uffe0\001\002\000\050\016\uffb4" +
    "\020\uffb4\025\uffb4\032\uffb4\034\uffb4\040\uffb4\041\uffb4\042" +
    "\uffb4\043\uffb4\045\uffb4\046\uffb1\047\uffb4\050\uffb4\051\uffb4" +
    "\052\uffb4\053\uffb4\054\uffb4\055\uffb4\061\uffb4\001\002\000" +
    "\006\016\uffe2\032\uffe2\001\002\000\006\016\uffdd\032\uffdd" +
    "\001\002\000\004\032\140\001\002\000\004\061\136\001" +
    "\002\000\004\062\126\001\002\000\022\015\035\017\026" +
    "\021\047\023\050\026\020\036\022\037\036\062\037\001" +
    "\002\000\046\016\uffb3\020\uffb3\025\uffb3\032\uffb3\034\uffb3" +
    "\040\uffb3\041\uffb3\042\uffb3\043\uffb3\045\uffb3\047\uffb3\050" +
    "\uffb3\051\uffb3\052\uffb3\053\uffb3\054\uffb3\055\uffb3\061\uffb3" +
    "\001\002\000\004\027\055\001\002\000\006\016\uffde\032" +
    "\uffde\001\002\000\006\016\uffcf\032\uffcf\001\002\000\010" +
    "\016\uffe6\032\uffe6\035\uffe6\001\002\000\004\024\057\001" +
    "\002\000\022\040\065\041\060\044\072\056\071\062\067" +
    "\063\074\064\061\065\063\001\002\000\016\044\072\056" +
    "\071\062\067\063\074\064\061\065\063\001\002\000\044" +
    "\016\uffb7\020\uffb7\025\uffb7\032\uffb7\034\uffb7\040\uffb7\041" +
    "\uffb7\042\uffb7\043\uffb7\045\uffb7\047\uffb7\050\uffb7\051\uffb7" +
    "\052\uffb7\053\uffb7\054\uffb7\055\uffb7\001\002\000\044\016" +
    "\uffc2\020\uffc2\025\uffc2\032\uffc2\034\uffc2\040\uffc2\041\uffc2" +
    "\042\115\043\114\045\uffc2\047\uffc2\050\uffc2\051\uffc2\052" +
    "\uffc2\053\uffc2\054\uffc2\055\uffc2\001\002\000\044\016\uffb8" +
    "\020\uffb8\025\uffb8\032\uffb8\034\uffb8\040\uffb8\041\uffb8\042" +
    "\uffb8\043\uffb8\045\uffb8\047\uffb8\050\uffb8\051\uffb8\052\uffb8" +
    "\053\uffb8\054\uffb8\055\uffb8\001\002\000\006\016\uffca\032" +
    "\uffca\001\002\000\016\044\072\056\071\062\067\063\074" +
    "\064\061\065\063\001\002\000\040\016\uffc9\020\uffc9\025" +
    "\uffc9\032\uffc9\034\uffc9\040\103\041\104\045\uffc9\047\uffc9" +
    "\050\100\051\101\052\102\053\105\054\106\055\107\001" +
    "\002\000\046\016\uffaf\020\uffaf\025\uffaf\032\uffaf\034\uffaf" +
    "\040\uffaf\041\uffaf\042\uffaf\043\uffaf\045\uffaf\046\uffaf\047" +
    "\uffaf\050\uffaf\051\uffaf\052\uffaf\053\uffaf\054\uffaf\055\uffaf" +
    "\001\002\000\044\016\uffbd\020\uffbd\025\uffbd\032\uffbd\034" +
    "\uffbd\040\uffbd\041\uffbd\042\uffbd\043\uffbd\045\uffbd\047\uffbd" +
    "\050\uffbd\051\uffbd\052\uffbd\053\uffbd\054\uffbd\055\uffbd\001" +
    "\002\000\016\044\072\056\071\062\067\063\074\064\061" +
    "\065\063\001\002\000\022\040\065\041\060\044\072\056" +
    "\071\062\067\063\074\064\061\065\063\001\002\000\044" +
    "\016\uffba\020\uffba\025\uffba\032\uffba\034\uffba\040\uffba\041" +
    "\uffba\042\uffba\043\uffba\045\uffba\047\uffba\050\uffba\051\uffba" +
    "\052\uffba\053\uffba\054\uffba\055\uffba\001\002\000\044\016" +
    "\uffb9\020\uffb9\025\uffb9\032\uffb9\034\uffb9\040\uffb9\041\uffb9" +
    "\042\uffb9\043\uffb9\045\uffb9\047\uffb9\050\uffb9\051\uffb9\052" +
    "\uffb9\053\uffb9\054\uffb9\055\uffb9\001\002\000\004\045\076" +
    "\001\002\000\044\016\uffb6\020\uffb6\025\uffb6\032\uffb6\034" +
    "\uffb6\040\uffb6\041\uffb6\042\uffb6\043\uffb6\045\uffb6\047\uffb6" +
    "\050\uffb6\051\uffb6\052\uffb6\053\uffb6\054\uffb6\055\uffb6\001" +
    "\002\000\044\016\uffb5\020\uffb5\025\uffb5\032\uffb5\034\uffb5" +
    "\040\uffb5\041\uffb5\042\uffb5\043\uffb5\045\uffb5\047\uffb5\050" +
    "\uffb5\051\uffb5\052\uffb5\053\uffb5\054\uffb5\055\uffb5\001\002" +
    "\000\022\040\065\041\060\044\072\056\071\062\067\063" +
    "\074\064\061\065\063\001\002\000\022\040\065\041\060" +
    "\044\072\056\071\062\067\063\074\064\061\065\063\001" +
    "\002\000\022\040\065\041\060\044\072\056\071\062\067" +
    "\063\074\064\061\065\063\001\002\000\016\044\072\056" +
    "\071\062\067\063\074\064\061\065\063\001\002\000\016" +
    "\044\072\056\071\062\067\063\074\064\061\065\063\001" +
    "\002\000\022\040\065\041\060\044\072\056\071\062\067" +
    "\063\074\064\061\065\063\001\002\000\022\040\065\041" +
    "\060\044\072\056\071\062\067\063\074\064\061\065\063" +
    "\001\002\000\022\040\065\041\060\044\072\056\071\062" +
    "\067\063\074\064\061\065\063\001\002\000\024\016\uffc8" +
    "\020\uffc8\025\uffc8\032\uffc8\034\uffc8\040\103\041\104\045" +
    "\uffc8\047\uffc8\001\002\000\024\016\uffc7\020\uffc7\025\uffc7" +
    "\032\uffc7\034\uffc7\040\103\041\104\045\uffc7\047\uffc7\001" +
    "\002\000\024\016\uffc6\020\uffc6\025\uffc6\032\uffc6\034\uffc6" +
    "\040\103\041\104\045\uffc6\047\uffc6\001\002\000\044\016" +
    "\uffc0\020\uffc0\025\uffc0\032\uffc0\034\uffc0\040\uffc0\041\uffc0" +
    "\042\115\043\114\045\uffc0\047\uffc0\050\uffc0\051\uffc0\052" +
    "\uffc0\053\uffc0\054\uffc0\055\uffc0\001\002\000\016\044\072" +
    "\056\071\062\067\063\074\064\061\065\063\001\002\000" +
    "\016\044\072\056\071\062\067\063\074\064\061\065\063" +
    "\001\002\000\044\016\uffbc\020\uffbc\025\uffbc\032\uffbc\034" +
    "\uffbc\040\uffbc\041\uffbc\042\uffbc\043\uffbc\045\uffbc\047\uffbc" +
    "\050\uffbc\051\uffbc\052\uffbc\053\uffbc\054\uffbc\055\uffbc\001" +
    "\002\000\044\016\uffbb\020\uffbb\025\uffbb\032\uffbb\034\uffbb" +
    "\040\uffbb\041\uffbb\042\uffbb\043\uffbb\045\uffbb\047\uffbb\050" +
    "\uffbb\051\uffbb\052\uffbb\053\uffbb\054\uffbb\055\uffbb\001\002" +
    "\000\044\016\uffc1\020\uffc1\025\uffc1\032\uffc1\034\uffc1\040" +
    "\uffc1\041\uffc1\042\115\043\114\045\uffc1\047\uffc1\050\uffc1" +
    "\051\uffc1\052\uffc1\053\uffc1\054\uffc1\055\uffc1\001\002\000" +
    "\024\016\uffc3\020\uffc3\025\uffc3\032\uffc3\034\uffc3\040\103" +
    "\041\104\045\uffc3\047\uffc3\001\002\000\024\016\uffc5\020" +
    "\uffc5\025\uffc5\032\uffc5\034\uffc5\040\103\041\104\045\uffc5" +
    "\047\uffc5\001\002\000\024\016\uffc4\020\uffc4\025\uffc4\032" +
    "\uffc4\034\uffc4\040\103\041\104\045\uffc4\047\uffc4\001\002" +
    "\000\044\016\uffbf\020\uffbf\025\uffbf\032\uffbf\034\uffbf\040" +
    "\uffbf\041\uffbf\042\115\043\114\045\uffbf\047\uffbf\050\uffbf" +
    "\051\uffbf\052\uffbf\053\uffbf\054\uffbf\055\uffbf\001\002\000" +
    "\044\016\uffbe\020\uffbe\025\uffbe\032\uffbe\034\uffbe\040\uffbe" +
    "\041\uffbe\042\115\043\114\045\uffbe\047\uffbe\050\uffbe\051" +
    "\uffbe\052\uffbe\053\uffbe\054\uffbe\055\uffbe\001\002\000\004" +
    "\061\127\001\002\000\004\064\130\001\002\000\004\022" +
    "\131\001\002\000\004\064\132\001\002\000\004\020\133" +
    "\001\002\000\004\026\020\001\002\000\004\032\135\001" +
    "\002\000\006\016\uffcb\032\uffcb\001\002\000\022\040\065" +
    "\041\060\044\072\056\071\062\067\063\074\064\061\065" +
    "\063\001\002\000\006\016\uffdc\032\uffdc\001\002\000\026" +
    "\015\035\017\026\021\047\023\050\024\uffe3\026\020\027" +
    "\uffe3\036\022\037\036\062\037\001\002\000\006\024\uffe4" +
    "\027\uffe4\001\002\000\022\040\065\041\060\044\072\056" +
    "\071\062\067\063\074\064\061\065\063\001\002\000\006" +
    "\034\uffd4\045\uffd4\001\002\000\004\045\150\001\002\000" +
    "\006\034\146\045\uffd5\001\002\000\022\040\065\041\060" +
    "\044\072\056\071\062\067\063\074\064\061\065\063\001" +
    "\002\000\004\045\uffd6\001\002\000\006\016\uffd7\032\uffd7" +
    "\001\002\000\004\025\152\001\002\000\022\015\035\017" +
    "\026\021\047\023\050\026\020\036\022\037\036\062\037" +
    "\001\002\000\006\016\154\032\uffce\001\002\000\022\015" +
    "\035\017\026\021\047\023\050\026\020\036\022\037\036" +
    "\062\037\001\002\000\006\016\uffcd\032\uffcd\001\002\000" +
    "\022\040\065\041\060\044\072\056\071\062\067\063\074" +
    "\064\061\065\063\001\002\000\004\047\160\001\002\000" +
    "\046\016\uffb2\020\uffb2\025\uffb2\032\uffb2\034\uffb2\040\uffb2" +
    "\041\uffb2\042\uffb2\043\uffb2\045\uffb2\047\uffb2\050\uffb2\051" +
    "\uffb2\052\uffb2\053\uffb2\054\uffb2\055\uffb2\061\uffb2\001\002" +
    "\000\004\020\162\001\002\000\022\015\035\017\026\021" +
    "\047\023\050\026\020\036\022\037\036\062\037\001\002" +
    "\000\006\016\uffcc\032\uffcc\001\002\000\004\062\067\001" +
    "\002\000\004\045\uffd8\001\002\000\004\045\167\001\002" +
    "\000\006\016\uffd9\032\uffd9\001\002\000\004\026\ufff7\001" +
    "\002\000\006\033\172\044\173\001\002\000\016\003\206" +
    "\004\200\005\211\006\202\007\203\011\201\001\002\000" +
    "\004\062\174\001\002\000\004\033\224\001\002\000\004" +
    "\045\176\001\002\000\004\033\177\001\002\000\016\003" +
    "\206\004\200\005\211\006\202\007\203\011\201\001\002" +
    "\000\014\010\uffeb\026\uffeb\032\uffeb\034\uffeb\045\uffeb\001" +
    "\002\000\004\046\213\001\002\000\014\010\uffe9\026\uffe9" +
    "\032\uffe9\034\uffe9\045\uffe9\001\002\000\014\010\uffe8\026" +
    "\uffe8\032\uffe8\034\uffe8\045\uffe8\001\002\000\014\010\uffec" +
    "\026\uffec\032\uffec\034\uffec\045\uffec\001\002\000\014\010" +
    "\uffef\026\uffef\032\uffef\034\uffef\045\uffef\001\002\000\014" +
    "\010\uffe7\026\uffe7\032\uffe7\034\uffe7\045\uffe7\001\002\000" +
    "\004\032\212\001\002\000\014\010\ufff0\026\ufff0\032\ufff0" +
    "\034\ufff0\045\ufff0\001\002\000\014\010\uffea\026\uffea\032" +
    "\uffea\034\uffea\045\uffea\001\002\000\006\010\ufff3\026\ufff3" +
    "\001\002\000\004\064\215\001\002\000\004\047\221\001" +
    "\002\000\004\035\216\001\002\000\004\035\217\001\002" +
    "\000\004\064\220\001\002\000\004\047\uffed\001\002\000" +
    "\004\030\222\001\002\000\014\003\206\004\200\005\211" +
    "\006\202\007\203\001\002\000\014\010\uffee\026\uffee\032" +
    "\uffee\034\uffee\045\uffee\001\002\000\016\003\206\004\200" +
    "\005\211\006\202\007\203\011\201\001\002\000\006\034" +
    "\226\045\ufff1\001\002\000\004\062\174\001\002\000\004" +
    "\045\ufff2\001\002\000\006\010\ufff4\026\ufff4\001\002\000" +
    "\004\026\020\001\002\000\004\032\233\001\002\000\006" +
    "\014\ufff5\026\ufff5\001\002\000\004\032\ufffe\001\002\000" +
    "\006\033\243\034\242\001\002\000\004\032\240\001\002" +
    "\000\006\014\ufffd\026\ufffd\001\002\000\010\014\ufffa\026" +
    "\ufffa\062\235\001\002\000\006\014\ufffb\026\ufffb\001\002" +
    "\000\004\062\235\001\002\000\016\003\206\004\200\005" +
    "\211\006\202\007\203\011\201\001\002\000\004\032\ufff8" +
    "\001\002\000\004\032\ufff9\001\002\000\004\002\000\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\244\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\003\011\004\010" +
    "\001\001\000\006\005\236\045\235\001\001\000\010\013" +
    "\016\014\015\046\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\004\230\047\231\001\001\000\002\001" +
    "\001\000\010\013\167\014\015\046\013\001\001\000\004" +
    "\015\020\001\001\000\050\015\033\016\044\017\042\020" +
    "\027\021\040\022\031\023\024\024\052\026\043\030\026" +
    "\031\023\036\045\037\050\040\030\041\041\042\037\043" +
    "\051\051\022\052\053\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\032\160\033\065\034\061\035\067\036\072" +
    "\037\050\040\030\041\041\042\037\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\032\150\033" +
    "\065\034\061\035\067\036\072\037\050\040\030\041\041" +
    "\042\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\050\015\033\016\044\017\042" +
    "\020\027\021\040\022\031\023\024\024\052\026\043\030" +
    "\026\031\023\036\045\037\050\040\030\041\041\042\037" +
    "\043\055\051\022\052\053\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\024\032\063\033\065\034" +
    "\061\035\067\036\072\037\050\040\030\041\041\042\037" +
    "\001\001\000\020\034\124\035\067\036\072\037\050\040" +
    "\030\041\041\042\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\034" +
    "\123\035\067\036\072\037\050\040\030\041\041\042\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\035\076\036\072\037\050\040\030\041\041" +
    "\042\037\001\001\000\024\032\074\033\065\034\061\035" +
    "\067\036\072\037\050\040\030\041\041\042\037\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\033\122\034\061" +
    "\035\067\036\072\037\050\040\030\041\041\042\037\001" +
    "\001\000\022\033\121\034\061\035\067\036\072\037\050" +
    "\040\030\041\041\042\037\001\001\000\022\033\120\034" +
    "\061\035\067\036\072\037\050\040\030\041\041\042\037" +
    "\001\001\000\020\034\117\035\067\036\072\037\050\040" +
    "\030\041\041\042\037\001\001\000\020\034\112\035\067" +
    "\036\072\037\050\040\030\041\041\042\037\001\001\000" +
    "\022\033\111\034\061\035\067\036\072\037\050\040\030" +
    "\041\041\042\037\001\001\000\022\033\110\034\061\035" +
    "\067\036\072\037\050\040\030\041\041\042\037\001\001" +
    "\000\022\033\107\034\061\035\067\036\072\037\050\040" +
    "\030\041\041\042\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\035" +
    "\116\036\072\037\050\040\030\041\041\042\037\001\001" +
    "\000\016\035\115\036\072\037\050\040\030\041\041\042" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\015\133\001\001\000\002\001\001" +
    "\000\002\001\001\000\024\032\136\033\065\034\061\035" +
    "\067\036\072\037\050\040\030\041\041\042\037\001\001" +
    "\000\002\001\001\000\050\015\033\016\044\017\042\020" +
    "\027\021\040\022\031\023\024\024\052\026\043\030\026" +
    "\031\023\036\045\037\050\040\030\041\041\042\037\043" +
    "\140\051\022\052\053\001\001\000\002\001\001\000\030" +
    "\027\144\032\142\033\065\034\061\035\067\036\072\037" +
    "\050\040\030\041\041\042\037\044\143\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\030\027" +
    "\144\032\142\033\065\034\061\035\067\036\072\037\050" +
    "\040\030\041\041\042\037\044\146\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\046\015\033" +
    "\016\152\017\042\020\027\021\040\022\031\023\024\024" +
    "\052\026\043\030\026\031\023\036\045\037\050\040\030" +
    "\041\041\042\037\051\022\052\053\001\001\000\002\001" +
    "\001\000\046\015\033\016\154\017\042\020\027\021\040" +
    "\022\031\023\024\024\052\026\043\030\026\031\023\036" +
    "\045\037\050\040\030\041\041\042\037\051\022\052\053" +
    "\001\001\000\002\001\001\000\024\032\156\033\065\034" +
    "\061\035\067\036\072\037\050\040\030\041\041\042\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\046\015\033\016\162\017\042\020\027\021\040" +
    "\022\031\023\024\024\052\026\043\030\026\031\023\036" +
    "\045\037\050\040\030\041\041\042\037\051\022\052\053" +
    "\001\001\000\002\001\001\000\016\025\165\036\164\037" +
    "\050\040\030\041\041\042\037\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\006\227\007\204\011\207\012\203" +
    "\001\001\000\004\050\174\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\006\206\007\204" +
    "\011\207\012\203\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\213\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\011\222\012\203\001\001\000\002\001" +
    "\001\000\012\006\224\007\204\011\207\012\203\001\001" +
    "\000\002\001\001\000\004\050\226\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\015\233\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\240" +
    "\045\235\001\001\000\002\001\001\000\004\045\244\001" +
    "\001\000\012\006\243\007\204\011\207\012\203\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



     public Program MPProgram;
        public Program getProgram(){
            return MPProgram;
        } 
    
    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
    public void report_error(String message, Object info) {
   
        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
        StringBuilder m = new StringBuilder("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuilder error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuilder error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        /* Add to the end of the StringBuilder error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuilder 'm', which contains
           an error message, out on a line. */
        System.err.println(m);
    }
   
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }






}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // var_ident ::= ID 
            {
              Variable_identifier RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Variable_identifier(id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_ident",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // ent_var ::= var_ident 
            {
              Entire_variable RESULT =null;
		int var_idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int var_idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable_identifier var_id = (Variable_identifier)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Entire_variable(var_id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ent_var",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // array_var ::= ent_var 
            {
              Array_variable RESULT =null;
		int e_varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e_varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Entire_variable e_var = (Entire_variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Array_variable(e_var); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("array_var",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // ind_var ::= array_var LCOR exp RCOR 
            {
              Indexed_variable RESULT =null;
		int ar_vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int ar_vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Array_variable ar_v = (Array_variable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Indexed_variable(ar_v, ex); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ind_var",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // var ::= ind_var 
            {
              Variable RESULT =null;
		int ind_vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ind_vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Indexed_variable ind_v = (Indexed_variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Variable(ind_v); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // var ::= ent_var 
            {
              Variable RESULT =null;
		int ent_vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ent_vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Entire_variable ent_v = (Entire_variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Variable(ent_v); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // factor ::= NOT factor 
            {
              Factor RESULT =null;
		int ftleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ftright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Factor ft = (Factor)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Factor(ft); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // factor ::= LPAREN exp RPAREN 
            {
              Factor RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Factor(ex); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // factor ::= NUMBER 
            {
              Factor RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Factor(num); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // factor ::= CONSTCHAR 
            {
              Factor RESULT =null;
		int chleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int chright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Character ch = (Character)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Factor(ch); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // factor ::= CONSTSTR 
            {
              Factor RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Factor(str); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // factor ::= var 
            {
              Factor RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable v = (Variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Factor(v); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // term ::= term DIVIDE factor 
            {
              Term RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // term ::= term TIMES factor 
            {
              Term RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // term ::= factor 
            {
              Term RESULT =null;
		int factleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int factright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Factor fact = (Factor)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Term(fact); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // sim_exp ::= MINUS term 
            {
              Simple_expression RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_exp",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // sim_exp ::= PLUS term 
            {
              Simple_expression RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_exp",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // sim_exp ::= sim_exp MINUS term 
            {
              Simple_expression RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_exp",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // sim_exp ::= sim_exp PLUS term 
            {
              Simple_expression RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_exp",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // sim_exp ::= term 
            {
              Simple_expression RESULT =null;
		int termleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Term term = (Term)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Simple_expression(term); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_exp",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // exp ::= sim_exp GREATER sim_exp 
            {
              Expression RESULT =null;
		int se1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int se1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Simple_expression se1 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int se2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int se2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_expression se2 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Greater(se1,se2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // exp ::= sim_exp GREATEREQ sim_exp 
            {
              Expression RESULT =null;
		int se1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int se1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Simple_expression se1 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int se2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int se2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_expression se2 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new GreaterE(se1,se2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // exp ::= sim_exp LESSEQ sim_exp 
            {
              Expression RESULT =null;
		int se1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int se1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Simple_expression se1 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int se2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int se2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_expression se2 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LessE(se1,se2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // exp ::= sim_exp LESS sim_exp 
            {
              Expression RESULT =null;
		int se1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int se1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Simple_expression se1 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int se2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int se2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_expression se2 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Less(se1,se2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // exp ::= sim_exp NEQ sim_exp 
            {
              Expression RESULT =null;
		int se1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int se1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Simple_expression se1 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int se2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int se2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_expression se2 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Nequal(se1,se2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // exp ::= sim_exp EQU sim_exp 
            {
              Expression RESULT =null;
		int se1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int se1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Simple_expression se1 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int se2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int se2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_expression se2 = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Equal(se1,se2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // exp ::= sim_exp 
            {
              Expression RESULT =null;
		int simeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int simeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_expression sime = (Simple_expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  new Expression(sime); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // repeat_stament ::= REPEAT staments UNTIL exp 
            {
              Repeat_stament RESULT =null;
		int stsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int stsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Staments sts = (Staments)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Repeat_stament(sts,ex); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("repeat_stament",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // for_stament ::= FOR ID ASSIGN NUMBER TO NUMBER DO c_stament SEMICOLON 
            {
              For_stament RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Integer m = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int stsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int stsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Compound_stament sts = (Compound_stament)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new For_stament(new Parameter(id,m),n,sts); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stament",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // while_stament ::= WHILE exp DO stament 
            {
              While_stament RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stament st = (Stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new While_stament(ex,st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stament",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // if_stament ::= IF exp THEN stament ELSE stament 
            {
              If_stament RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int st1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int st1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Stament st1 = (Stament)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int st2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int st2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stament st2 = (Stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new If_stament(ex,st1,st2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stament",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // if_stament ::= IF exp THEN stament 
            {
              If_stament RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stament st = (Stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new If_stament(ex,st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stament",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // struct_stament ::= repeat_stament 
            {
              Structured_stament RESULT =null;
		int r_stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int r_stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Repeat_stament r_st = (Repeat_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Structured_stament(r_st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("struct_stament",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // struct_stament ::= for_stament 
            {
              Structured_stament RESULT =null;
		int f_stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int f_stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		For_stament f_st = (For_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Structured_stament(f_st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("struct_stament",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // struct_stament ::= while_stament 
            {
              Structured_stament RESULT =null;
		int w_stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int w_stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		While_stament w_st = (While_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Structured_stament(w_st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("struct_stament",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // struct_stament ::= if_stament 
            {
              Structured_stament RESULT =null;
		int if_stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int if_stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		If_stament if_st = (If_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Structured_stament(if_st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("struct_stament",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // struct_stament ::= c_stament 
            {
              Structured_stament RESULT =null;
		int c_stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c_stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Compound_stament c_st = (Compound_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Structured_stament(c_st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("struct_stament",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // output_val ::= exp 
            {
              Output_value RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Output_value(ex); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("output_val",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // writes ::= output_val 
            {
              Writes RESULT =null;
		int ovleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ovright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Output_value ov = (Output_value)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Writes(); RESULT.add(ov); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("writes",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // writes ::= output_val COMMA writes 
            {
              Writes RESULT =null;
		int ovleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int ovright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Output_value ov = (Output_value)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int wrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int wrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Writes wr = (Writes)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 wr.add(ov); RESULT = wr; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("writes",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // write_s ::= WRITE LPAREN writes RPAREN 
            {
              Write_stament RESULT =null;
		int wrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int wrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Writes wr = (Writes)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Write_stament(wr); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("write_s",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // input_var ::= var 
            {
              Input_variable RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable v = (Variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Input_variable(v); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("input_var",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // read_s ::= READ LPAREN input_var RPAREN 
            {
              Read_stament RESULT =null;
		int i_vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int i_vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Input_variable i_v = (Input_variable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Read_stament(i_v); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("read_s",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // proc_id ::= ID 
            {
              Procedure_iden RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Procedure_iden(id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("proc_id",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // proc_s ::= proc_id 
            {
              Procedure_stament RESULT =null;
		int p_idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int p_idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Procedure_iden p_id = (Procedure_iden)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Procedure_stament(p_id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("proc_s",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // assign_s ::= var ASSIGN exp 
            {
              Assign_stament RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Variable v = (Variable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expression ex = (Expression)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Assign_stament(v,ex); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign_s",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // sim_stament ::= write_s 
            {
              Simple_stament RESULT =null;
		int w_sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int w_sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Write_stament w_s = (Write_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Simple_stament(w_s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_stament",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // sim_stament ::= read_s 
            {
              Simple_stament RESULT =null;
		int r_sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int r_sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Read_stament r_s = (Read_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Simple_stament(r_s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_stament",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sim_stament ::= proc_s 
            {
              Simple_stament RESULT =null;
		int p_sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int p_sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Procedure_stament p_s = (Procedure_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Simple_stament(p_s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_stament",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sim_stament ::= assign_s 
            {
              Simple_stament RESULT =null;
		int as_sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int as_sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Assign_stament as_s = (Assign_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Simple_stament(as_s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sim_stament",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // stament ::= struct_stament 
            {
              Stament RESULT =null;
		int st_stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int st_stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Structured_stament st_st = (Structured_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Stament(st_st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stament",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // stament ::= sim_stament 
            {
              Stament RESULT =null;
		int sim_stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sim_stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_stament sim_st = (Simple_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Stament(sim_st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stament",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // staments ::= stament SEMICOLON 
            {
              Staments RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Stament st = (Stament)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new Staments(); RESULT.add(st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("staments",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // staments ::= stament SEMICOLON staments 
            {
              Staments RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Stament st = (Stament)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Staments sts = (Staments)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		sts.add(st); RESULT = sts; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("staments",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // c_stament ::= BEGIN END 
            {
              Compound_stament RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("c_stament",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // c_stament ::= BEGIN staments END 
            {
              Compound_stament RESULT =null;
		int stsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int stsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Staments sts = (Staments)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new Compound_stament(sts); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("c_stament",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // t_id ::= error 
            {
              Type_ident RESULT =null;
		 System.out.println("Type Expected"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("t_id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // t_id ::= STRING 
            {
              Type_ident RESULT =null;
		 RESULT = new Type_ident(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("t_id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // t_id ::= BOOLEAN 
            {
              Type_ident RESULT =null;
		 RESULT = new Type_ident(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("t_id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // t_id ::= CHAR 
            {
              Type_ident RESULT =null;
		 RESULT = new Type_ident(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("t_id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // t_id ::= INTEGER 
            {
              Type_ident RESULT =null;
		 RESULT = new Type_ident(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("t_id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // simple_t ::= t_id 
            {
              Simple_type RESULT =null;
		int tidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tidright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type_ident tid = (Type_ident)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Simple_type (tid); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_t",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // index_r ::= NUMBER DOT DOT NUMBER 
            {
              Index_range RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Index_range(n1,n2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("index_r",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // array_t ::= ARRAY LCOR index_r RCOR OF simple_t 
            {
              Array_type RESULT =null;
		int ind_rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int ind_rright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Index_range ind_r = (Index_range)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sim_tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sim_tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_type sim_t = (Simple_type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Array_type(ind_r,sim_t); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("array_t",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // type ::= array_t 
            {
              Type RESULT =null;
		int atleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int atright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Array_type at = (Array_type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Type(at); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // type ::= simple_t 
            {
              Type RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Simple_type st = (Simple_type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Type(st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // parameters ::= ID COLON type 
            {
              Parameters RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type tipo = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Parameters(id,tipo); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("parameters",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // parameters ::= ID COLON type COMMA parameters 
            {
              Parameters RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Type tipo = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int pmsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pmsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Parameters pms = (Parameters)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 pms.add(new Parameter(id,tipo)); RESULT = pms; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("parameters",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // p_dec ::= PROCEDURE ID LPAREN parameters RPAREN COLON type SEMICOLON 
            {
              Procedure_d RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Parameters p = (Parameters)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Type tipo = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Procedure_d (id,tipo,p); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("p_dec",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // p_dec ::= PROCEDURE ID COLON type 
            {
              Procedure_d RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type tipo = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Procedure_d(id,tipo); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("p_dec",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // proc_dec ::= p_dec block_p SEMICOLON 
            {
              Procedure_dec RESULT =null;
		int pdleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int pdright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Procedure_d pd = (Procedure_d)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int blleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int blright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Block_p bl = (Block_p)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Procedure_dec(pd,bl); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("proc_dec",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // p_d_p ::= 
            {
              Procedure_dec_part RESULT =null;
		 RESULT = new Procedure_dec_part(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("p_d_p",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // p_d_p ::= proc_dec p_d_p 
            {
              Procedure_dec_part RESULT =null;
		int pdleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pdright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Procedure_dec pd = (Procedure_dec)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pdpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pdpright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Procedure_dec_part pdp = (Procedure_dec_part)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 pdp.add(pd); RESULT= pdp; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("p_d_p",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // v_dec ::= ID COLON type 
            {
              Variable_d RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Type tipo = (Type)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Variable_d(id,tipo); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("v_dec",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // v_dec ::= ID COMMA v_dec 
            {
              Variable_d RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int vdleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable_d vd = (Variable_d)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 vd.add(id); RESULT = vd; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("v_dec",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_dec ::= 
            {
              Variable_dec RESULT =null;
		 RESULT = new Variable_dec(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_dec",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // var_dec ::= v_dec SEMICOLON var_dec 
            {
              Variable_dec RESULT =null;
		int vdleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Variable_d vd = (Variable_d)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int var_dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int var_dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable_dec var_d = (Variable_dec)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 var_d.add(vd); RESULT = var_d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_dec",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // v_d_p ::= 
            {
              Variable_dec_part RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("v_d_p",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // v_d_p ::= VAR var_dec 
            {
              Variable_dec_part RESULT =null;
		int vdleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable_dec vd = (Variable_dec)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Variable_dec_part(vd); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("v_d_p",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // block_p ::= v_d_p c_stament 
            {
              Block_p RESULT =null;
		int vdpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vdpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Variable_dec_part vdp = (Variable_dec_part)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int c_sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c_sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Compound_stament c_s = (Compound_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Block_p(vdp,c_s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("block_p",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // block ::= v_d_p p_d_p c_stament 
            {
              Block RESULT =null;
		int vdpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vdpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Variable_dec_part vdp = (Variable_dec_part)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int pdpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pdpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Procedure_dec_part pdp = (Procedure_dec_part)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int c_sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c_sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Compound_stament c_s = (Compound_stament)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Block (vdp,pdp,c_s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= PROGRAM ID SEMICOLON block DOT 
            {
              Program RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int blockleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int blockright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Block block = (Block)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		parser.MPProgram  = new Program (id,block); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

