
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 11 11:29:02 CST 2017
//----------------------------------------------------

package p_minipascal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 33;
  public static final int FUNCTION = 10;
  public static final int CHAR = 3;
  public static final int INTEGER = 2;
  public static final int GREATER = 40;
  public static final int LPAREN = 34;
  public static final int REPEAT = 17;
  public static final int ARRAY = 7;
  public static final int LESS = 41;
  public static final int FOR = 15;
  public static final int MINUS = 31;
  public static final int RCOR = 37;
  public static final int WRITE = 29;
  public static final int RPAREN = 35;
  public static final int AND = 46;
  public static final int NOT = 44;
  public static final int SEMICOLON = 24;
  public static final int OR = 45;
  public static final int COMMA = 26;
  public static final int BEGIN = 20;
  public static final int UNTIL = 18;
  public static final int PLUS = 30;
  public static final int ASSIGN = 47;
  public static final int LESSEQ = 39;
  public static final int IF = 11;
  public static final int ID = 48;
  public static final int DOT = 27;
  public static final int OF = 22;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int PROGRAM = 23;
  public static final int NUMBER = 50;
  public static final int CONSTSTR = 49;
  public static final int NEQ = 42;
  public static final int TIMES = 32;
  public static final int EQU = 43;
  public static final int COLON = 25;
  public static final int ELSE = 12;
  public static final int READ = 28;
  public static final int TO = 16;
  public static final int WHILE = 13;
  public static final int LCOR = 36;
  public static final int THEN = 19;
  public static final int END = 21;
  public static final int GREATEREQ = 38;
  public static final int STRING = 5;
  public static final int CONSTCHAR = 51;
  public static final int FALSE = 9;
  public static final int VAR = 6;
  public static final int DO = 14;
}

