
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 26 17:09:19 CST 2017
//----------------------------------------------------

package p_minipascal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 32;
  public static final int CHAR = 3;
  public static final int INTEGER = 2;
  public static final int GREATER = 39;
  public static final int LPAREN = 33;
  public static final int REPEAT = 17;
  public static final int ARRAY = 7;
  public static final int LESS = 40;
  public static final int FOR = 15;
  public static final int MINUS = 30;
  public static final int RCOR = 36;
  public static final int WRITE = 28;
  public static final int RPAREN = 34;
  public static final int AND = 45;
  public static final int NOT = 43;
  public static final int SEMICOLON = 23;
  public static final int OR = 44;
  public static final int COMMA = 25;
  public static final int BEGIN = 19;
  public static final int PLUS = 29;
  public static final int ASSIGN = 46;
  public static final int LESSEQ = 38;
  public static final int IF = 11;
  public static final int ID = 47;
  public static final int DOT = 26;
  public static final int OF = 21;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int PROGRAM = 22;
  public static final int NUMBER = 49;
  public static final int CONSTSTR = 48;
  public static final int NEQ = 41;
  public static final int TIMES = 31;
  public static final int EQU = 42;
  public static final int COLON = 24;
  public static final int ELSE = 12;
  public static final int READ = 27;
  public static final int TO = 16;
  public static final int WHILE = 13;
  public static final int LCOR = 35;
  public static final int THEN = 18;
  public static final int END = 20;
  public static final int GREATEREQ = 37;
  public static final int STRING = 5;
  public static final int CONSTCHAR = 50;
  public static final int FALSE = 9;
  public static final int VAR = 6;
  public static final int PROCEDURE = 10;
  public static final int DO = 14;
}

